### ISSUE TITLE
Support latest stable upstream release

### ISSUE THREAD

**Issue by ganto** [debops-contrib/ansible-roundcube#19]
Currently, the role is only tested with the latest Roundcube 1.1.x release. Make sure that the latest 1.2.x stable and maybe even 1.3-beta are supported.

**Comment by cultcom** [comment]
I tested version 1.2.4 which is generally working but has some fuckup with Net_Sieve.

The latest official Net_Sieve version is 1.3.4. The INSTALL file only mentions 1.3.2 as minimum but the plugin itself has a dependancy to 1.5.0 in it's composer files?!

Seems like the roundcube people forked the lib to do their own changes: https://github.com/roundcube/roundcubemail

This might be another reason to install from the "-complete" release files, as they contain those libs, instead of deploying it from git.
